### ISSUE TITLE
denoised or predicted counts - normalized?

### ISSUE THREAD

**Issue by shobhitagrawal1** [ZhangLabGT/scDisInFact#3]
Dear Zhang and Mehak, 
Thank you for this great tool and congratulations on the paper! I really like the methodology devised by you. I have been trying it out now, and the general workflow is excellent and easy to follow. 
I would be really grateful if you could answer the following question:
a) In the demo you have shown that the counts obtained after prediction or denoising can be normalized and then scaled, meaning that the counts are unnormalized counts although they appear as non-integers, is that correct? Upon analyzing the code I found that the input to the model (query counts) are normalized. Is the output (mu) then still unnormalized counts

**Comment by PeterZZQ** [comment]
Hi,

Thank you for your interest in our work. 

Yes, the predicted count is not normalized or scaled, you should normalize it before using the count. And it is also true that we used the normalized count as the input of the VAE. We used the normalized count as the input for the stability of the model. Actually, the input and output do not have to be the same in the model, it is all about what ground truth data is used in the reconstruction loss that decide the output format.

**Comment by shobhitagrawal1** [comment]
Dear Peter, Thank you very much. That was very helpful. I have several other queries (sorry for the bother!), but for now, can I save the model somehow for future denoising/predicting etc, somehow?

**Comment by PeterZZQ** [comment]
Yes, you can save the model easily with `torch.save(scdisinfact_model, "scdisinfact_model.pt")` and load the model with `scdisinfact_model = torch.load("scdisinfact_model.pt")`.

**Comment by shobhitagrawal1** [comment]
thank you very much.
